name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Configure CMake with Ninja
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: Build with Ninja
      run: cmake --build build --parallel
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v4
      if: github.ref_name == 'main'
      with:
        name: image-viewer
        path: build/**/*.exe