name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Configure CMake with Ninja
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: Build with Ninja
      run: cmake --build build --parallel
